export default {
    RECEIVE_SEATS: 'RECEIVE_SEATS',
    ADD_SEAT: 'ADD_SEAT',
    UPDATE_SEAT: 'UPDATE_SEAT',
    OPEN_SEAT_DETAILS: 'OPEN_SEAT_DETAILS',
    CLOSE_SEAT_DETAILS: 'CLOSE_SEAT_DETAILS',
    DELETE_SEAT: 'DELETE_SEAT',
    MOVE_SEAT: 'MOVE_SEAT',
    SELECTION_MODE_ON: 'SELECTION_MODE_ON',
    SELECTION_MODE_OFF: 'SELECTION_MODE_OFF',
    MOVE_SEAT: 'MOVE_SEAT',
    ASSIGN_USER: 'ASSIGN_USER'
};