export default {
    LIST_USERS: 'LIST_USERS',
    RECEIVE_USERS: 'RECEIVE_USERS',
    OPEN_USER_DETAILS: 'OPEN_USER_DETAILS',
    CLOSE_USER_DETAILS: 'CLOSE_USER_DETAILS',
    SHOW_LIST: 'SHOW_LIST',
    HIDE_LIST: 'HIDE_LIST',
};